# Generated by Django 6.0.3 on 2026-03-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('VEHICULES', 'Véhicules'), ('IMMOBILIER', 'Immobilier'), ('AMEUBLEMENT', 'Ameublement'), ('DIVERS', 'Divers')], default='DIVERS', max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
