# Generated by Django 6.0.3 on 2026-08-03 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_annonce_auteur_alter_annonce_titre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='categorie',
            field=models.CharField(choices=[('VEHICULES', 'Véhicules'), ('IMMOBILIER', 'Immobilier'), ('AMEUBLEMENT', 'Ameublement'), ('DIVERS', 'Divers')], max_length=50),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='titre',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='annonces.annonce')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'annonce')},
            },
        ),
    ]
