# Generated by Django 6.0.3 on 2026-08-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0006_alter_annonce_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='type_annonce',
            field=models.CharField(choices=[('OFFRE', 'Offre'), ('DEMANDE', 'Demande')], default='OFFRE', max_length=10, verbose_name="Type d'annonce"),
        ),
    ]
